Cytomata is an open-source script collection that integrates tools and methods used for mass cytometry (CyTOF) analysis into an automated pipeline.
Author: Lev Petrov


master.R
Installation of required packages, folder management, all the most important settings.
General usage guide is also included here as comments.
Plotting preferences have to be changed separately in corresponding scripts.



